/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Activity5_Frame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MALILONG_CpE121
 */
public class StudentRegistrationForm extends javax.swing.JFrame {

    DefaultTableModel model;
    

    /**
     * Creates new form StudentRegistrationForm
     */
    public StudentRegistrationForm() {
        initComponents();
        model=(DefaultTableModel)BASTATABLE.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addstudentBUTTON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BASTATABLE = new javax.swing.JTable();
        studentidBLANK = new javax.swing.JTextField();
        nameBLANK = new javax.swing.JTextField();
        ageBLANK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ClearFormButton = new javax.swing.JButton();
        program_ComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudentBUTTON.setText("ADD STUDENT");
        addstudentBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(addstudentBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 161, -1, -1));

        BASTATABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Program", "Age"
            }
        ));
        jScrollPane1.setViewportView(BASTATABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 206, 573, 234));
        getContentPane().add(studentidBLANK, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 21, 333, -1));
        getContentPane().add(nameBLANK, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 53, 333, -1));
        getContentPane().add(ageBLANK, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 333, -1));

        jLabel1.setText("Student ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 70, -1));

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, -1));

        jLabel3.setText("Program:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        ClearFormButton.setText("CLEAR FORM");
        ClearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFormButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        program_ComboBox.setEditable(true);
        program_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COE", "CHS", "CABE", "CSP", "CCIS", "SHS", "JHS" }));
        program_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                program_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(program_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addstudentBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBUTTONActionPerformed
        // TODO add your handling code here:
        String studentid=studentidBLANK.getText();
        String name=nameBLANK.getText();
        String program=program_ComboBox.getSelectedItem().toString();
        String age=ageBLANK.getText();
        
        model.addRow(new Object[]{studentid,name ,program, age} );
        studentidBLANK.setText("");
        nameBLANK.setText("");
        ageBLANK.setText("");
    }//GEN-LAST:event_addstudentBUTTONActionPerformed

    private void ClearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFormButtonActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);  // Clears all rows
    }//GEN-LAST:event_ClearFormButtonActionPerformed

    private void program_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_program_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_program_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BASTATABLE;
    private javax.swing.JButton ClearFormButton;
    private javax.swing.JButton addstudentBUTTON;
    private javax.swing.JTextField ageBLANK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameBLANK;
    private javax.swing.JComboBox<String> program_ComboBox;
    private javax.swing.JTextField studentidBLANK;
    // End of variables declaration//GEN-END:variables
}
